# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxf2vr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dxf2vrpagegalleryimage',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dxf2vrpagegalleryimage',
            name='layer',
            field=models.CharField(max_length=250),
        ),
    ]
