# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dxf2vr', '0002_auto_20170914_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dxf2vrpagegalleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
