# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dxf2vr', '0003_dxf2vrpagematerialimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dxf2vrpagematerialimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dxf2vrpagematerialimage',
            name='page',
        ),
        migrations.DeleteModel(
            name='Dxf2VrPageMaterialImage',
        ),
    ]
