# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dxf2vr', '0003_auto_20170917_0152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dxf2VrPageGalleryImage',
            new_name='Dxf2VrPageMaterialImage',
        ),
    ]
