# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxf2vr', '0005_dxf2vrpagematerialimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxf2vrpagematerialimage',
            name='pattern',
            field=models.BooleanField(default=False),
        ),
    ]
