# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxf2vr', '0006_dxf2vrpagematerialimage_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxf2vrpage',
            name='shadows',
            field=models.BooleanField(default=False),
        ),
    ]
