# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxf2vr', '0007_dxf2vrpage_shadows'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxf2vrpage',
            name='fly_camera',
            field=models.BooleanField(default=False),
        ),
    ]
