# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxf2vr', '0008_dxf2vrpage_fly_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxf2vrpage',
            name='double_face',
            field=models.BooleanField(default=False),
        ),
    ]
